
version: 2

models:
  - name: fact_page_views
    description: page view-grained facts table
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: page_type
        tests:
          - not_null
      
  - name: fact_daily_product_page_performance
    description: Tracks daily performance of each product page - pageviews, orders,cart additions
    columns:
      - name: event_date
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null

  - name: int_event_type_details
    description: Intermediate table tracking pages where various types of events happened
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
