
version: 2

models:
  - name: stg_users
    description: Contains information on greenery users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
      - name: became_user_at
        tests:
          - not_null
      
  - name: stg_addresses
    description: Contains address details for greenery users
    columns:
      - name: address_id
        tests:
          - unique
          - not_null

  - name: stg_events
    description: Contains event details for sessions on greenery
    columns:
      - name: event_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: Contains details on orders made by greenery users
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: user_id
        tests:
          - not_null

  - name: stg_order_items
    description: Contains details on items included in orders
    columns:
      - name: order_item_id
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: quantity
        tests:
          - positive_values

  - name: stg_products
    description: Dimension table tracking products available for order
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: price
        tests:
          - not_null
          - positive_values
      - name: quantity
        tests:
          - positive_values

  - name: stg_promos
    description: Contains details on discounts
    columns:
      - name: promo_id
        tests:
          - unique
          - not_null